name: release

on:
  push:
    tags:
      - v-*

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  create_wheels_and_upload_to_pypi:
    runs-on: ubuntu-latest
    name: Create new release
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build wheels and upload
      run: |
        pip install twine wheel
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
